### ISSUE TITLE
Deploy Website & Update README 

### ISSUE THREAD

**Issue by teke85** [teke85/portfolio_project-setup#7]
- Link to the online version of the portfolio website 
https://teke85.github.io/portfolio_project-setup/

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @teke85 , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡
 
✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ZikaZaki** [comment]
Hi, @teke85 
I think your website is perfect. Everything is working just fine, but I think it would be better to use some transition for the social media icons.

**Comment by yasinabdmahmood** [comment]
it would be better to include the link to your GitHub page under the Live Demo section as per Microverse standards

![Capture 1PNG](https://user-images.githubusercontent.com/97350474/179691036-12eb991d-dde2-4749-9f67-87d066a387d0.PNG)

**Comment by ghost** [comment]
Great job! 👍 

wouldn't be nice to add focus to your contact form to aid accessibility.

**Comment by teke85** [comment]
> Great job! 👍
> 
> wouldn't be nice to add focus to your contact form to aid accessibility.

Hi @Apt2tell Thank you for your comment, I actually added focus to my form but after I deployed my project the website kept loading from the top. I will research more on how to make the website load correctly with focus added to the form.

**Comment by teke85** [comment]
> it would be better to include the link to your GitHub page under the Live Demo section as per Microverse standards
> 
> ![Capture 1PNG](https://user-images.githubusercontent.com/97350474/179691036-12eb991d-dde2-4749-9f67-87d066a387d0.PNG)

Hi @yasinabdmahmood Thank you for your comment. I will do likewise.

**Comment by teke85** [comment]
> Hi, @teke85 I think your website is perfect. Everything is working just fine, but I think it would be better to use some transition for the social media icons.

@ZikaZaki Thank you for your comment. I will add transitions to the social media icons.
